---
- name: Check
  import_tasks: check.yml
  tags:
    - check

- name: Install
  become: yes
  import_tasks: install.yml
  tags:
    - install
  when: nomad_installed_version.rc != 0 or nomad_force_install or nomad_version not in nomad_installed_version.stdout