---
- name: Check
  import_tasks: check.yml
  tags:
    - check

- name: Install
  become: yes
  import_tasks: install.yml
  tags:
    - install
  when: consul_installed_version.rc != 0 or consul_force_install or consul_version not in consul_installed_version.stdout
